# dataset
datasets:
  kid_icarus:
    level_start_ends:
        "../data/kid_icarus/start_ends.txt"
    raw:
      "../data/kid_icarus/raw"
    intermediate:
      "../data/kid_icarus/intermediate"
    processed: 
      "../data/kid_icarus/processed"
    cropped:
        "../data/kid_icarus/cropped"
    vglc_annotated:
        "../data/kid_icarus/vglc_annotated"
    vglc_levels:
      "../data/kid_icarus/vglc_levels"
    vglc_mapping:
        "../data/kid_icarus/kidIcarus.json"
    level_format:
        "bmp"
  
  megaman:
    level_start_ends:
      "../data/megaman/start_ends.txt"
    raw:
      "../data/megaman/raw"
    intermediate:
      "../data/megaman/intermediate"
    processed: 
      "../data/megaman/processed"
    cropped: 
      "../data/megaman/cropped"
    vglc_annotated:
        "../data/megaman/vglc_annotated"
    vglc_levels:
      "../data/megaman/vglc_levels"
    vglc_mapping:
        "../data/megaman/MM.json"
    level_format:
        "bmp"
  
  smb:
    level_start_ends:
      "../data/smb/start_ends.txt"
    raw:
      "../data/smb/raw"
    intermediate:
      "../data/smb/intermediate"
    processed: 
      "../data/smb/processed"
    cropped:
      "../data/smb/cropped"
    vglc_annotated:
        "../data/smb/vglc_annotated"
    vglc_levels:
      "../data/smb/vglc_levels"
    vglc_mapping:
        "../data/smb/smb.json"
    level_format:
        "png"
  
  zelda:
    level_start_ends:
      "../data/zelda/start_ends.txt"
    raw:
      "../data/zelda/raw"
    intermediate:
      "../data/zelda/intermediate"
    processed: 
      "../data/zelda/processed"
    cropped:
      "../data/zelda/cropped"
    vglc_annotated:
        "../data/zelda/vglc_annotated"
    vglc_levels:
      "../data/zelda/vglc_levels"
    vglc_mapping:
        "../data/zelda/zelda.json"
    level_format:
        "png"
  
  load_runner:
    level_start_ends:
      "../data/load_runner/start_ends.txt"
    raw:
      "../data/load_runner/raw"
    intermediate:
      "../data/load_runner/intermediate"
    processed: 
      "../data/load_runner/processed"
    cropped:
      "../data/load_runner/cropped"
    vglc_annotated:
        "../data/load_runner/vglc_annotated"
    vglc_levels:
      "../data/load_runner/vglc_levels"
    vglc_mapping:
        "../data/load_runner/zelda.json"
    level_format:
        "png"




# [image_processing]
image_preprocessing:
    inter_height:
            228
    inter_width:
            256
    tile_height:
            16
    tile_width:
            16
    proc_width:
            48
    proc_height:
            48